"""standardize_terminology_client_to_offerer

Revision ID: 3dfb508aad3a
Revises: 0c45cddd0492
Create Date: 2025-07-21 22:24:12.270502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dfb508aad3a'
down_revision = '0c45cddd0492'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
