name: Web App CI

on:
  push:
    branches: [ main ]
    paths:
      - 'Mercenary_Dev/web-app/**'
      - '.github/workflows/webapp-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'Mercenary_Dev/web-app/**'
      - '.github/workflows/webapp-ci.yml'
  workflow_dispatch:

jobs:
  webapp-ci:
    name: Type-check, Lint, Test, Build (web-app)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Mercenary_Dev/web-app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: Mercenary_Dev/web-app/package-lock.json

      - name: Install dependencies (npm ci)
        run: npm ci --no-audit --no-fund
        continue-on-error: true

      - name: Fallback install (npm install)
        if: failure()
        run: npm install --no-audit --no-fund

      - name: TypeScript type-check
        run: npm run type-check
        env:
          CI: true

      - name: Lint
        run: npm run lint
        env:
          CI: true

      - name: Tests
        run: npm run test
        env:
          CI: true

      - name: Build
        run: npm run build
        env:
          NEXT_TELEMETRY_DISABLED: '1'
          CI: true
